// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCItK998Uv6oSXh1u3NjftI2nrp3uThFhY',
    appId: '1:1097834847194:web:ce740de052b1c4f86a3ee3',
    messagingSenderId: '1097834847194',
    projectId: 'app-stock-plus',
    authDomain: 'app-stock-plus.firebaseapp.com',
    storageBucket: 'app-stock-plus.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNZhoXSAc94Gv36hKRjvTZ1TJMNUy8NOI',
    appId: '1:1097834847194:android:2769c2c1b956006d6a3ee3',
    messagingSenderId: '1097834847194',
    projectId: 'app-stock-plus',
    storageBucket: 'app-stock-plus.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS4qzQZw8xWhtXF0Ljm39vyQF-4xztXV8',
    appId: '1:1097834847194:ios:fca147d702c1c6626a3ee3',
    messagingSenderId: '1097834847194',
    projectId: 'app-stock-plus',
    storageBucket: 'app-stock-plus.firebasestorage.app',
    iosBundleId: 'com.example.appProjeto',
  );
}
